---
title: "Timer"
author: "Maj Jason Freels"
date: "March 28, 2016"
output: slidy_presentation
---

# Define the functions

```{r, echo=FALSE}

################# This demonstrates point reduction #############################
#This script will generate 15 PDF plots at various point counts

#Definition of function to compute the first passage CDF matrix in the LT domain
SMP.firstpass.cdf <- function(s) {
  tmp1 <- p*ft(s)  
  tmp2 <- solve(Id-tmp1)
  tmp3 <- solve(Id*tmp2)
  return(1/s*tmp1%*%tmp2%*%tmp3)
}

#Definition of function to compute the first passage PDF matrix in the LT domain
SMP.firstpass.pdf <- function(s) {
  tmp1 <- p*ft(s)  
  tmp2 <- solve(Id-tmp1)
  tmp3 <- solve(Id*tmp2)
  return(tmp1%*%tmp2%*%tmp3)
}

#Definition of function to compute the transient probability matrix in the LT domain
SMP.transprob.t <- function(s) {
  J <- matrix(1,ncol=n,nrow=n)
  tmp1 <- p*ft(s)  
  tmp2 <- solve(Id-tmp1) 
  return(1/s*tmp2%*%(Id-Id*(tmp1%*%J))) 
}

#Definition of function to compute the expected visits to a state matrix in the LT domain
SMP.expected.visits.to.state <- function(s) {
  tmp1 <- p*ft(s)  
  tmp2 <- solve(Id-tmp1) 
  return(1/s*(tmp2-Id)) 
}

#Definition of function to compute the expected time in state matrix in the LT domain
SMP.expected.time.in.state <- function(s) {
  J <- matrix(1,ncol=n,nrow=n)
  tmp1 <- p*ft(s)  
  tmp2 <- solve(Id-tmp1) 
  return(1/s^2*tmp2%*%(Id-Id*(tmp1%*%J))) 
}

#Definition of function to compute the probability of transistioning to state 0 times matrix in the LT domain
SMP.prob.trans.to.state.0.times <- function(s) {
  J <- matrix(1,ncol=n,nrow=n)
  tmp1 <- p*ft(s)  
  tmp2 <- solve(Id-tmp1)
  tmp3 <- solve(Id*tmp2)
  g <- tmp1%*%tmp2%*%tmp3
  return(1/s*(J-g)) 
}

#Definition of function to compute the probability of transistioning to state 1 or less times matrix in the LT domain
SMP.prob.trans.to.state.1.times <- function(s) {
  J <- matrix(1,ncol=n,nrow=n)
  tmp1 <- p*ft(s)  
  tmp2 <- solve(Id-tmp1)
  tmp3 <- solve(Id*tmp2)
  g <- tmp1%*%tmp2%*%tmp3
  return(1/s*(J-g*(J%*%(Id*g)))) 
}

#Definition of function to compute the probability of transistioning to state 2 or less times matrix in the LT domain
SMP.prob.trans.to.state.2.times <- function(s) {
  J <- matrix(1,ncol=n,nrow=n)
  tmp1 <- p*ft(s)  
  tmp2 <- solve(Id-tmp1)
  tmp3 <- solve(Id*tmp2)
  g <- tmp1%*%tmp2%*%tmp3
  return(1/s*(J-g*(J%*%((Id*g)^2)))) 
}


#Definition of the EULER function to invert LTs
#The first arguement is a vector of functions to invert
#The second arguement is the Time and the others are optional parameters
#The output is a array of matricies indexed by the input functions
euler_par <- function(input_f_vec,T,A = 18.4,Ntr = 15,num=11) {
  m <- length(input_f_vec)
  w = c(1/2,rep(1,Ntr-1), rev(cumsum(choose((num),0:(num))))/(2^(num)))
  SU <- array(0,c(m,n,n))
  for (j in 0:(Ntr+num)) { 
     for (k in 1:m) {
       SU[k,,] <- SU[k,,] + w[j+1]*(-1)^(j)*Re(input_f_vec[[k]](A/(2*T)+ j*pi/T*1i))
     }
  }
  return(exp(A/2)/T*SU)
}
```

#Unsafe, hopefully quicker VGAM dfisk

```{r,echo=false}
dfisk_quick <- function(x, scale = 1, shape1.a, log = FALSE)
  dsinmad(x, scale = scale, shape1.a = shape1.a, shape3.q = 1, log = log)

dsinmad <- function(x, scale = 1, shape1.a, shape3.q, log = FALSE) {

  if (!is.logical(log.arg <- log) || length(log) != 1)
    stop("bad input for argument 'log'")
  rm(log)

  LLL      <- max(length(x),     length(shape1.a),
                  length(scale), length(shape3.q))
  x        <- rep(x,         length.out = LLL)
  shape1.a <- rep(shape1.a,  length.out = LLL)
  scale    <- rep(scale,     length.out = LLL)
  shape3.q <- rep(shape3.q,  length.out = LLL)

  Loglik <- rep(log(0), length.out = LLL)
  xok <- (x > 0) & !is.na(x)  # Avoids log(x) if x<0, and handles NAs
  Loglik[xok] <- log(shape1.a[xok]) + log(shape3.q[xok]) +
                 (shape1.a[xok]-1) * log(x[xok]) -
                shape1.a[xok] * log(scale[xok]) -
           (1 + shape3.q[xok]) * log1p((x[xok]/scale[xok])^shape1.a[xok])
  x.eq.0 <- (x == 0) & !is.na(x)
  Loglik[x.eq.0] <- log(shape1.a[x.eq.0]) + log(shape3.q[x.eq.0]) -
                    shape1.a[x.eq.0] * log(scale[x.eq.0])
  Loglik[is.na(x)]  <- NA
  Loglik[is.nan(x)] <- NaN
  Loglik[x == Inf]  <- log(0)

  exp(Loglik)
}
```

# Define the Extra Problem

```{r}

#library(VGAM)
# EXTRA Prob
n<-3

Id <- diag(1,n)

Zero <- rep(0,n)

p <- matrix(c(0,0,0,0.14,0,0.86,0,1,0),nrow=n,ncol=n,byrow=T)

#Defining temporary matrix
temp <- matrix(0,nrow=n,ncol=n,byrow=T)

#Defining a temporary variable for the frequency variable in the LT domain
temp_s <- 0

#function that calculates the LT for for the f-tilde matrix 
ft <- function(s) {
  #Checking if the LTs were just calculated for this value of s
  if (s == temp_s) {
    return(temp)
  }

   #Computing the numeric integration for the LT of the 5 Weibull waiting time distributions
   ft1r <- function(t) {dlnorm(t,5.8,.8384)*exp(-Re(s)*t)*cos(Im(s)*t)}
   ft1i <- function(t) {dlnorm(t,5.8,.8384)*exp(-Re(s)*t)*sin(Im(s)*t)}
   temp1 <- integrate(ft1r,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value - 
            integrate(ft1i,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value*1i
   ft2r <- function(t) {dfisk_quick(t,34.231,2.097)*exp(-Re(s)*t)*cos(Im(s)*t)}
   ft2i <- function(t) {dfisk_quick(t,34.231,2.097)*exp(-Re(s)*t)*sin(Im(s)*t)}
   temp2 <- integrate(ft2r,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value - 
            integrate(ft2i,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value*1i
   ft3r <- function(t) {dlnorm(t,5.128,1.766)*exp(-Re(s)*t)*cos(Im(s)*t)}
   ft3i <- function(t) {dlnorm(t,5.128,1.766)*exp(-Re(s)*t)*sin(Im(s)*t)}
   temp3 <- integrate(ft3r,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value - 
            integrate(ft3i,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value*1i
   
   
   
#   ft4r <- function(t) {dunif(t,0,10)*exp(-Re(s)*t)*cos(Im(s)*t)}
#   ft4i <- function(t) {dunif(t,0,10)*exp(-Re(s)*t)*sin(Im(s)*t)}
#   temp4 <- integrate(ft4r,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value - 
#            integrate(ft4i,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value*1i
#   ft5r <- function(t) {dchisq(t,2)*exp(-Re(s)*t)*cos(Im(s)*t)}
#   ft5i <- function(t) {dchisq(t,2)*exp(-Re(s)*t)*sin(Im(s)*t)}
#   temp5 <- integrate(ft5r,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value - 
#            integrate(ft5i,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value*1i
#   ft6r <- function(t) {dweibull(t,1.2,2)*exp(-Re(s)*t)*cos(Im(s)*t)}
#   ft6i <- function(t) {dweibull(t,1.2,2)*exp(-Re(s)*t)*sin(Im(s)*t)}
#   temp6 <- integrate(ft6r,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value - 
#            integrate(ft6i,0,Inf,subdivisions=10000,rel.tol=1e-10,stop.on.error=FALSE)$value*1i
   
   #Defining a matrix to output from this function
   output <- matrix(
              c(0.000,0,0,
                temp3,0.000,temp2,   
                0.000,temp1,0
                   ),nrow=n,ncol=n,byrow=T)

   #Updating the "global" variable temp_s
   temp_s <<- s

   #Updating the "global" matrix variable temp
   temp <<- output

   return(output)
}
```

#Part A)

```{r}
Rt <- function(s) {1/s-SMP.firstpass.cdf(s)}

Re(Rt(0.0001)[2,1])
Re(Rt(0.0000001)[2,1])
Re(Rt(0.0000000001)[2,1])


Rt_int <- function(s) {1/s*Rt(s)}

mean1 <- euler_par(c(Rt_int),100000000)
mean1[1,2,1]
```


#Part F)

```{r}
Hazu21 <- euler_par(c(SMP.firstpass.pdf),.001)
Hazu21[1,2,1]

Hazd21 <- euler_par(c(SMP.firstpass.cdf),.001)
Hazd21[1,2,1]


Haz <- Hazu21/(1-Hazd21)
Haz
```

#Part B)

```{r}
#P32 <- euler_par(c(transprobt),30)
#P32[1,3,2]

# Save PDF plots of each...
for(numPoints in c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 400, 800, 1200, 1600, 2000)){
    t1 <- Sys.time()
  
  
  #numPoints <- 60
  plotUpperBound <- 2000
  
  Haz <- array(NA,c(2, numPoints ,n,n))
  
  #Rprof("HazProfile.out")
  
  
  hazIndex <- 1
  iVals = seq(1, plotUpperBound, length=numPoints)
  
  for (i in iVals){
     Haz[,hazIndex  ,,] <- euler_par(c(SMP.firstpass.cdf,SMP.firstpass.pdf), i/40)
     hazIndex <- hazIndex + 1
  }
  
  #Rprof(NULL)
  #summaryRprof("HazProfile.out")
  
  plotPath = sprintf("PLOTS/plot_%dpoints.pdf", numPoints);
  pdf(plotPath, width=11,height=8.5,paper='special');
  plot( iVals/40 ,Haz[2,,2,1]/(1-Haz[1,,2,1]),type="l",xlab="Time",ylab="");
  dev.off()
  
  t2 <- Sys.time()
  
  print(sprintf("Time results for %d points = %f seconds.", numPoints,  difftime(t2, t1, units="secs") ));
  
}

  ## My check ran about 11.5 minutes
```
